schema_version = "1.0.0"

id = "topolyx_blender_extension"
name = "Topolyx Blender Extension"
version = "0.0.1"
tagline = "Import and export Blender meshes to the Topolyx format"
maintainer = "0x309 <ymh0402@proton.me>"
type = "add-on"

tags = ["Import-Export"]

blender_version_min = "5.1.0"

license = [
    "SPDX:MIT",
]
