schema_version = "1.0.0"

id = "topolyx_import_export"
name = "Topolyx Import/Export"
version = "1.0.0"
tagline = "Import and export Blender meshes to the Topolyx format"
maintainer = "0x309 <ymh0402@proton.me>"
type = "add-on"
website = "https://github.com/ym-0x309/topolyx_import_export"

tags = ["Import-Export"]

blender_version_min = "5.1.0"

license = [
    "SPDX:GPL-3.0-or-later",
]
